knp_snappy:
    pdf:
        enabled: true
        binary: '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64' # Ou le chemin vers wkhtmltopdf
        options: []

    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
