vich_uploader:
    db_driver: orm
    mappings:
        post_images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
