# config/services.yaml

# ------------------------------------------------------------------
# PARAMÈTRES
# ------------------------------------------------------------------
parameters:
    # Chemin absolu vers le dossier d'upload des photos d'avis
    avis_photos_directory: '%kernel.project_dir%/public/uploads/avis'

# ------------------------------------------------------------------
# SERVICES
# ------------------------------------------------------------------
services:
    # Configuration par défaut pour vos services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Enregistrement automatique des services (commandes, événements, etc.)
        public: false       # Par défaut, vos services ne sont pas publics

    # Enregistre vos contrôleurs comme services publics
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
        public: true

    # Charge toutes les classes de src/, à l’exception de quelques dossiers
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Migrations/'
            - '../src/Tests/'
            - '../src/Kernel.php'
