parameters:
    upload_directory: '%kernel.project_dir%/public/images'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Déclaration explicite des services sans créer de référence circulaire
    Symfony\Component\Finder\Finder:
        class: Symfony\Component\Finder\Finder
        public: false
        shared: false # Important pour Finder qui n'est pas un service partagé

    Symfony\Component\Filesystem\Filesystem:
        class: Symfony\Component\Filesystem\Filesystem
        public: false

    # Configuration de la commande
    App\Command\GenerateRepositoriesCommand:
        tags: ['console.command']
        # Les arguments seront injectés automatiquement grâce à l'autowiring