# config/services.yaml
parameters:
    # Répertoires d'upload
    upload_directory: '%kernel.project_dir%/public/images'
    cv_directory: '%kernel.project_dir%/public/uploads/cv'
    lettre_directory: '%kernel.project_dir%/public/uploads/lettre_motivation'
    diplome_directory: '%kernel.project_dir%/public/uploads/diplome'
    candidature_cv_directory: '%kernel.project_dir%/public/uploads/candidatures'
    
    # Configuration Twilio
    twilio.sid: '%env(TWILIO_SID)%'
    twilio.token: '%env(TWILIO_TOKEN)%'
    twilio.from: '%env(TWILIO_PHONE)%'

services:
    # Defaults
    _defaults:
        autowire: true      # Active l'autowiring
        autoconfigure: true # Active l'autoconfiguration
        public: false       # Rend les services privés par défaut

    # Services partagés
    Symfony\Component\Finder\Finder:
        class: Symfony\Component\Finder\Finder
        shared: false # Non partagé pour éviter les conflits

    Symfony\Component\Filesystem\Filesystem: ~

    # Commandes
    App\Command\GenerateRepositoriesCommand:
        tags: ['console.command']

    # Service Twilio avec injection explicite des paramètres
    App\Service\TwilioService:
        arguments:
            $sid: '%twilio.sid%'
            $token: '%twilio.token%'
            $from: '%twilio.from%'

    # Autres services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
